apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-sc
  csi:
    driver: file.csi.azure.com
    volumeHandle: warrisonblazex123#warrisonblaze#public
    volumeAttributes:
      storageAccount: warrisonblazex123
      shareName: warrisonblaze
    nodeStageSecretRef:
      name: azure-secret
      namespace: default

