apiVersion: v1
kind: Service
metadata:
  name: webapp-nodeport
spec:
  selector:
    app: webapp
  ports:
  - name: c01-nginx
    port: 80
    targetPort: 80
    nodePort: 30080

  - name: c02-python
    port: 5000
    targetPort: 5000
    nodePort: 30500
  type: NodePort

