apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    command:
      - "sh"
      - "-c"
      - "echo 'Hello from c01' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    ports:
      - containerPort: 80

  - name: python-container
    image: python:3.9-slim
    command:
      - "sh"
      - "-c"
      - "echo 'Hello from c02' > index.html && python -m http.server 5000"
    ports:
      - containerPort: 5000

