apiVersion: v1
kind: Pod
metadata:
  name: pod-cpu-max-fail
  namespace: rq-demo
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    resources:
      limits:
        cpu: "1"
