apiVersion: v1
kind: Pod
metadata:
  name: pod-memory-fail
  namespace: rq-demo
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    resources:
      limits:
        memory: "10Gi"
